# ------ Syntax ------
[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = ['coffee']

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['slim']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']

[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = ['jade', 'pug']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]]
repo = 'kh3phr3n/python-syntax'
on_ft = 'python'
hook_add = "source ~/.vim/setting/plugins/python-syntax.vim"

[[plugins]]
repo = 'wavded/vim-stylus'
on_ft = 'stylus'
# --------------------

# ------ Unite ------
[[plugins]]
repo = 'Shougo/unite.vim'
on_cmd = ['Unite']

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['unite.vim']

[[plugins]]
repo = 'kmnk/vim-unite-giti'
on_source = ['unite.vim']
# --------------------

# ------ 補完 ------
# [[plugins]]
# repo = 'Shougo/neocomplcache.vim'
# on_i = 1
# hook_add = 'source ~/.vim/setting/plugins/neocomplcache.vim'
#
# [[plugins]]
# repo = 'Shougo/neocomplcache-rsense.vim' # neocomplcacheの設定
# on_i = 1
# hook_add = 'source ~/.vim/setting/plugins/rsense.vim'
# --------------------

# ------ Ruby ------
[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = ['ruby']

# neovimでエラー
# [[plugins]]
# repo = 'todesking/ruby_hl_lvar.vim'
# on_ft = ['ruby']

[[plugins]]
repo = 'vim-scripts/ruby-matchit'
on_ft = ['ruby']

[[plugins]]
repo = 'ngmy/vim-rubocop'
on_ft = ['ruby']
# --------------------

# ------ Python ------
[[plugins]] # コード補完
repo = 'davidhalter/jedi-vim'
on_ft = ['python']

[[plugins]] # tabで補完
repo = 'ervandew/supertab'
on_ft = ['python']
hook_add = 'source ~/.vim/setting/plugins/jedi-vim.vim'

[[plugins]]
repo = 'vim-scripts/Flake8-vim'
on_ft = ['python']
hook_add = 'source ~/.vim/setting/plugins/flake8-vim.vim'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = ['python']

[[plugins]]
repo = 'Townk/vim-autoclose'
on_ft = ['python']
# --------------------

# ------ Markdown and preview ------
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown']

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['markdown']
# --------------------

[[plugins]] # SQL formatter
repo = 'vim-scripts/SQLUtilities'
on_ft = ['sql', 'no ft']

[[plugins]] # Text format
repo = 'vim-scripts/Align'
on_source = ['SQLUtilities']
